sudo: required

services:
    - docker

before_install:
    - docker pull electracoin/electra

script:
    - docker run electracoin/electra /bin/bash -c "su - ecadev; git clone -b $TRAVIS_BRANCH --single-branch https://github.com/Electra-project/Electra.git; cd Electra; qmake; make"
    - docker run electracoin/electra /bin/bash -c "su - ecadev; git clone -b $TRAVIS_BRANCH --single-branch https://github.com/Electra-project/Electra.git; cd Electra; qmake GUI=0; make"
